Secondary script for integration checks.
Manta-Network/manta-types pull request #13
Opened 2021-06-29 08:54 UTC by ghzlatarev

* Added a script to detect if integrations have been successful.
* Clones all sync branches and builds. Expects success.
* Only triggered if the initial integration check (which detects failure) has failed.

2021-07-06 07:13 UTC, ghzlatarev commented on scripts/check_integrations_success.sh
> +BRANCH_STRING="some_sync_branch_name"
This is the variable you gotta edit manually for the routine to work out.
All the sync branches should use the same name.

2021-08-09 16:16 UTC, stechu requested changes
Can you write a doc for the `sync-branch` design?
I don't feel confident to merge the branch before understanding the design.

2021-08-11 11:05 UTC, ghzlatarev commented
> Can you write a doc for the `sync-branch` design?
> I don't feel confident to merge the branch before understanding the design.

Please check this doc out:
https://github.com/Manta-Network/Manta/wiki/How-to-update-Manta-dependencies-in-downstream-repositories.

We've already merged this functionality in other repos though.

2021-08-16 05:30 UTC, stechu commented
> > Can you write a doc for the `sync-branch` design?
> > I don't feel confident to merge the branch before understanding the design.
> 
> Please check this doc out:
> https://github.com/Manta-Network/Manta/wiki/How-to-update-Manta-dependencies-in-downstream-repositories.
> 
> We've already merged this functionality in other repos though.

I cannot open the link.

2021-08-16 08:44 UTC, ghzlatarev commented
> > > Can you write a doc for the `sync-branch` design?
> > > I don't feel confident to merge the branch before understanding the design.
> > 
> > 
> > Please check this doc out:
> > https://github.com/Manta-Network/Manta/wiki/How-to-update-Manta-dependencies-in-downstream-repositories.
> > We've already merged this functionality in other repos though.
> 
> I cannot open the link.

https://github.com/Manta-Network/Manta/wiki/How-to-update-Manta-dependencies-in-downstream-repositories.

> > > Can you write a doc for the `sync-branch` design?
> > > I don't feel confident to merge the branch before understanding the design.
> > 
> > 
> > Please check this doc out:
> > https://github.com/Manta-Network/Manta/wiki/How-to-update-Manta-dependencies-in-downstream-repositories .
> > We've already merged this functionality in other repos though.
> 
> I cannot open the link.

Oops there was a mistake in the link . Should work now. This is the manta wiki.

2021-09-21 05:12 UTC, closed without merging