Refactor Storage
Manta-Network/manta-types pull request #25
Opened 2021-08-16 05:24 UTC by stechu

This is part of refactoring `pallet-manta-pay` storage.

- [ ] fix sharding function (use `Blake2s` to produce a random bit as the sharding function)
- [ ] new shard data structure design
- [ ] improve the efficiencies of operations regards to a single shard

2021-09-21 21:28 UTC, bhgomes commented on manta-data/Cargo.toml
> +manta-error = { path = "../../manta-error", default-features = false }
These need to be changed back to the `git` dependencies.

2021-09-21 21:37 UTC, bhgomes commented on manta-data/src/lib.rs
> +/// Note: these values are still correct, however should not be used anymore since we are using parity codec to serdes
If you want, you can mark this as deprecated:

```rust
#[deprecated = "These values are still correct, but should not be used anymore.
    We are using parity codec for serdes."]
/// ...
pub const MINT_PAYLOAD_SIZE: usize = 184;
```

2021-09-21 21:40 UTC, bhgomes requested changes
See `Cargo.toml` and other comment. LGTM.

2021-09-22 03:03 UTC, Kevingislason reviewed
LGTM. I suppose you know getting rid of `BuildMetadata` will break `manta-signer`, right?

2021-09-22 03:51 UTC, bhgomes commented
> I suppose you know getting rid of `BuildMetadata` will break `manta-signer`, right?

Yeah, you're right. I forgot about this. I think it will also break `manta-api`, we need to keep it for now.

2021-09-22 10:38 UTC, stechu commented on manta-data/src/lib.rs
> +/// Note: these values are still correct, however should not be used anymore since we are using parity codec to serdes
How about just remove them?

2021-09-22 15:01 UTC, bhgomes commented on manta-data/src/lib.rs
> +/// Note: these values are still correct, however should not be used anymore since we are using parity codec to serdes
Yeah, I would just remove them.

2021-09-22 15:44 UTC, stechu commented
The following function need to be implemented after the merkle tree implementation is merged into `manta-crypto`:
```rust
impl BuildMetadata for MantaAsset {
```
@bhgomes

2021-09-22 22:30 UTC, bhgomes commented
See Manta-Network/manta-crypto/pull/27.

2021-09-29 16:03 UTC, merged